### ISSUE TITLE
[Feature Request] Work Item Checklist: Add/Remove items in templates

### ISSUE THREAD

**Issue by tcpaddock** [mohitbagra/azure-devops-extensions#12]
Great work on the Work item checklist extension! It would be great if it were possible to add or remove shared checklist items in work item templates similar to the Tags (Add) and Tags (Remove) field options.

**Comment by mohitbagra** [comment]
You can add shared checklist for a work item type by going to Checklist settings page. Work item templates wont work because it only allows 1st party fields in it, no extensions.
