### ISSUE TITLE
Bug Bash ADO Extension

### ISSUE THREAD

**Issue by dawnmheine** [mohitbagra/azure-devops-extensions#13]
While trying to enter a Bug Bash Item (Bug), after filling in the title and description I am getting this error and do not know how to correct it:

TF401320: Rule Error for field Description. Error code: Required, InvalidEmpty. 12 additional errors occurred during validation of the work item. Please correct all errors and try again.

**Comment by mohitbagra** [comment]
Looks like you have set "Auto accept" in your bug bash instance. So when you create a bug bash item, it will use the entered Title and description to create a Bug, but looks like your "Bug" work item type has another required field which is not being sent by the creation logic.
You need to create a work item template that fills in this required field and set that template in your bug bash instance. This way, when your bug bash item is accepted, it will use that template to fill all other required fields
