### ISSUE TITLE
Mandatory checkbox field

### ISSUE THREAD

**Issue by enrrpark** [mohitbagra/azure-devops-extensions#14]
I have this ticked as part of a checklist which is added to each ticket but tickets can be saved/moved to closed etc without any interaction taking place with the fields.

Is there a way to enforce rules for the fields which have to be filled in?

I'd like to use this as a definition of done checklist for tickets going to the closed column of a board. 

![image](https://user-images.githubusercontent.com/642509/64266736-04a65b80-cf2d-11e9-896f-7294b8e19f87.png)

**Comment by mohitbagra** [comment]
This extension is not designed to work with any work item field. So "Mandatory" just acts like a guidance to users. It doesn't block work item save or state change. This functionality will fall beyond my original idea for the extension so I dont have any plans to implement this as well.
