### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by kahughes** [mohitbagra/azure-devops-extensions#2]
Hi - I have a couple of customer's working with us using bug bash who have found that they can only access using Chrome (previously used IE).  This only appears to after updates at the weekend, should this be the case?  Thanks

**Comment by mohitbagra** [comment]
Which  browser specifically is the issue here? Just IE11? In order to use some latest javascript features 9which IE11 doesnt support), I have dropped IE support from the extension
