### ISSUE TITLE
Label Filter Not working

### ISSUE THREAD

**Issue by ThorntonHranicky** [mohitbagra/azure-devops-extensions#33]
When selecting to filter a task by the label, it returns no results when there are clearly results to return:
![image](https://user-images.githubusercontent.com/70349140/91496723-3f15b080-e882-11ea-80ca-10118a7d17fe.png)
![image](https://user-images.githubusercontent.com/70349140/91496751-4b9a0900-e882-11ea-9387-9ae91b4b685b.png)

**Comment by hallmansm** [comment]
I have the same issue. Would like to have a list labeled DOR, label for Acceptance Criteria, label for DOD. And filter to each one. But as the previous user said, filtering by any label hides everything. That same result happens with Default labels created in settings, and labels created directly within a card.

**Comment by ThorntonHranicky** [comment]
@hallmansm I found the solution but never updated this. The issue was really dumb honestly your tags have to be lowercase. Once I made them content vs Content, the filtering worked perfectly.
