### ISSUE TITLE
Support Azure DevOps Server

### ISSUE THREAD

**Issue by HaGGi13** [mohitbagra/azure-devops-extensions#34]
I really appreciate this extension, but cannot use it, because in our company Azure DevOps Server in operation only.
Is there any chance or plan to support Azure DevOps Server in the future as well?

Thanks in advance for your response.

**Comment by alessandrocaetanob** [comment]
+1 for this

**Comment by HaGGi13** [comment]
As nothing happened here since years and the original repository was took over and is better/well maintained, I close this issue, because I'm not interested in to use this fork anymore.
