### ISSUE TITLE
Checklist extension infinite load + chrome window crash

### ISSUE THREAD

**Issue by hamouda06** [mohitbagra/azure-devops-extensions#8]
Hello,

We face an issue with CheckList extension.
Actually, when we open a workItem in chrome we have an infinite loader on checkList Area and the chrome window crash a few seconds later.

![image](https://user-images.githubusercontent.com/15197032/60020084-93763c80-968f-11e9-9492-32996e0abe46.png)

The version that we use is : 

![image](https://user-images.githubusercontent.com/15197032/60020154-b7d21900-968f-11e9-89d2-ad50e0b1e562.png)

And this the console log I have : 

![image](https://user-images.githubusercontent.com/15197032/60020207-d59f7e00-968f-11e9-9b30-9a7df7c3d5ac.png)

Can you please take a look at this issue?

Thank you,
Hamouda

**Comment by mohitbagra** [comment]
This should have been fixed on Friday. It was a bug in Azure Devops extension sdk. A fix was deployed late last week. Can you check again and if you can still see this issue, can you tell me where are you opening the work item from? (backlog, board, sprint or somewhere else)

**Comment by hamouda06** [comment]
Hello,
I tested it again this morning and yes it's fixed thank you I will close the issue.
Best Regards,
Hamouda

**Comment by synvolt** [comment]
Hi @mohitbagra, myself and a few other users are experiencing this at the moment.
//Andrei
