### ISSUE TITLE
reporting

### ISSUE THREAD

**Issue by Lau82** [mohitbagra/azure-devops-extensions#9]
Hello! Is there a way to show reports on the check list items? I am trying to find a query that includes it with no luck. 

Thank you

**Comment by mohitbagra** [comment]
No. The checklist data is stored outside of work item data, so its not stored in any work item field value. So you cannot write a query to filter out work items based on checklist items

**Comment by Lau82** [comment]
Thanks for your response! I thought so, I wanted to give it a try.
